version: '2'
services:
  nginx:
    build: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    network_mode: bridge

#docker-compose exec kafka kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic starship
#docker-compose exec kafka kafka-topics --delete --zookeeper zookeeper:2181 --topic starship
#docker-compose exec kafka kafka-topics --list --zookeeper zookeeper:2181
