eureka:
  client:
    service-url:
      defaultZone: http://localhost:8180/eureka
management:
  endpoints:
    web:
      base-path: /act
      exposure:
        include: '*'
testConfig: config-service-application-classpath
